/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as AdminAccessRouteImport } from './routes/admin-access'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminRegistrationRequestsRouteImport } from './routes/admin.registration-requests'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminInstructorsRouteImport } from './routes/admin.instructors'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminBoardRouteImport } from './routes/admin.board'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/admin-access',
  path: '/admin-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationRequestsRoute =
  AdminRegistrationRequestsRouteImport.update({
    id: '/registration-requests',
    path: '/registration-requests',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorsRoute = AdminInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoardRoute = AdminBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-access': typeof AdminAccessRoute
  '/competitions': typeof CompetitionsRoute
  '/courses': typeof CoursesRoute
  '/gallery': typeof GalleryRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/registration-requests': typeof AdminRegistrationRequestsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-access': typeof AdminAccessRoute
  '/competitions': typeof CompetitionsRoute
  '/courses': typeof CoursesRoute
  '/gallery': typeof GalleryRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/registration-requests': typeof AdminRegistrationRequestsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-access': typeof AdminAccessRoute
  '/competitions': typeof CompetitionsRoute
  '/courses': typeof CoursesRoute
  '/gallery': typeof GalleryRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/registration-requests': typeof AdminRegistrationRequestsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-access'
    | '/competitions'
    | '/courses'
    | '/gallery'
    | '/instructor'
    | '/login'
    | '/news'
    | '/register'
    | '/student'
    | '/admin/board'
    | '/admin/competitions'
    | '/admin/courses'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/instructors'
    | '/admin/news'
    | '/admin/registration-requests'
    | '/admin/students'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-access'
    | '/competitions'
    | '/courses'
    | '/gallery'
    | '/instructor'
    | '/login'
    | '/news'
    | '/register'
    | '/student'
    | '/admin/board'
    | '/admin/competitions'
    | '/admin/courses'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/instructors'
    | '/admin/news'
    | '/admin/registration-requests'
    | '/admin/students'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-access'
    | '/competitions'
    | '/courses'
    | '/gallery'
    | '/instructor'
    | '/login'
    | '/news'
    | '/register'
    | '/student'
    | '/admin/board'
    | '/admin/competitions'
    | '/admin/courses'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/instructors'
    | '/admin/news'
    | '/admin/registration-requests'
    | '/admin/students'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminAccessRoute: typeof AdminAccessRoute
  CompetitionsRoute: typeof CompetitionsRoute
  CoursesRoute: typeof CoursesRoute
  GalleryRoute: typeof GalleryRoute
  InstructorRoute: typeof InstructorRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-access': {
      id: '/admin-access'
      path: '/admin-access'
      fullPath: '/admin-access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registration-requests': {
      id: '/admin/registration-requests'
      path: '/registration-requests'
      fullPath: '/admin/registration-requests'
      preLoaderRoute: typeof AdminRegistrationRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructors': {
      id: '/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AdminInstructorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/board': {
      id: '/admin/board'
      path: '/board'
      fullPath: '/admin/board'
      preLoaderRoute: typeof AdminBoardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBoardRoute: typeof AdminBoardRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminInstructorsRoute: typeof AdminInstructorsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminRegistrationRequestsRoute: typeof AdminRegistrationRequestsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBoardRoute: AdminBoardRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminInstructorsRoute: AdminInstructorsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminRegistrationRequestsRoute: AdminRegistrationRequestsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminAccessRoute: AdminAccessRoute,
  CompetitionsRoute: CompetitionsRoute,
  CoursesRoute: CoursesRoute,
  GalleryRoute: GalleryRoute,
  InstructorRoute: InstructorRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
